# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
#   - By default, all script lines are interpreted as batch
#   - For more information see: https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Test against this version of Node.js
environment:
  nodejs_version: "lts"
  slack_incoming_hook:
    secure: v42ynvt9jDeqjrWYYdht6cGuwa/iSjI7G4SJZAfhEDX5LYuwjnKDmgzDKTi0LRyM3r+nrQNyTHkWGhmCXPs9+2XCVWg5YGv/nB9MRcB+oBQ=

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g cordova@8.0.0 ionic@3.19.0
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  # Output useful info for debugging.
  - ionic --info
  # Run Linter
  - npm run lint
  # Build for browser
  - ionic cordova prepare
  - ionic cordova build browser

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  # Output useful info for debugging.
  - ionic --info
  # run tests
  - npm run test-ci
  # http://help.appveyor.com/discussions/problems/2917-upgrade-chrome-browser-please#comment_39289617
  - choco install googlechrome
  - npm run e2e

# to disable automatic tests
test: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Slack
  - provider: Slack
    incoming_webhook:
      secure: ${slack_incoming_hook}
