#
# CircleCI 2.0 configuration file
#
# Reference: https://circleci.com/docs/2.0/configuration-reference/
#
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    working_directory: ~/repo

    steps:

      ###########
      # PREPARE #
      ###########

      # Checkout repoistory
      - checkout

      # Install global dependencies
      # Ionic - needed for ionic CLI
      # Cordova - for build
      - run:
          name: Install Global Dependencies
          command: |
            sudo yarn global add ionic@latest cordova

      # Restore cached node_modules folder if there is one
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install from package.json using yarn
      - run:
          name: Install Packages
          command: yarn install

      # Save node_modules folder to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Print Ionic Debig Info
      - run:
          name: Ionic Info
          command: ionic info

      #################
      # LINT AND TEST #
      #################

      # Lint
      - run:
          name: Lint
          command: yarn run lint

      # Ionic Doctor Check
      - run:
          name: Ionic Doctor
          command: ionic doctor check

      # Run Unit Tests
      - run:
          name: Run Unit Tests
          environment:
            JUNIT_REPORT_PATH: ./test-results/karma-unit
            JUNIT_REPORT_NAME: results.xml
          command: yarn run test-ci

      # Upload Coverage Information To Codecov
      - run:
          name: Upload Coverage To Codecov
          environment:
            CODECOV_TOKEN: 7bb5fc6f-e960-4a51-8069-6e4c07d4d847
          command: cat ./coverage/lcov.info | ./node_modules/.bin/codecov

      # Run e2e Tests
      - run:
          name: E2E Test
          environment:
            JUNIT_REPORT_PATH: ./test-results/protractor-e2e,
            JUNIT_REPORT_NAME: junit_e2e_results.xml
          command: yarn run e2e-ci

      #################
      # STORE RESULTS #
      #################

      # Store Test Results For Build Test Summary On Build Dashboard
      - store_test_results:
          path: ./test-results/

      # Store Artifacts of Unit and E2E Test Results in Test Artiface
      - store_artifacts:
          path: ./test-results/
          destination: test-results

      # Store Artifacts of Unit Test Coverage in Test Artifacts
      - store_artifacts:
          path: ./coverage/
          destination: test-coverage

      - persist_to_workspace:
          root: ~/repo
          paths:
            - /*

  build-project:
    docker:
      - image: circleci/node:8.11-browsers

    working_directory: ~/repo

    steps:

      #############
      # BUILD APP #
      #############

      - attach_workspace:
          at: ~/repo

      # Prepare App
      - run:
          name: Prepare
          command: ionic cordova prepare

      # Build Browser
      - run:
          name: Build Browser
          command: ionic cordova build browser

      # Store Browser Build Artifacts
      - store_artifacts:
          path: ./platforms/browser/www/
          destination: build/browser

      # Build Android
      - run:
          name: Build Android
          command: ionic cordova build android

      # Store Android Build Artifacts
      - store_artifacts:
          path: ./platforms/android/build/outputs/
          destination: build/android

workflows:
  version: 2
  test-and-build:
    jobs:
      - build
      - build-project:
          requires:
            - build
